# https://sculpin.io/documentation/configuration/
#sculpin:
#    ignore: [ 'css/' ]

sculpin_content_types:
    post:
        permalink: blog/:year/:month/:day/:filename/
        type: path
        path: _posts
